version: "3.1"

services:
  db:
    image: docker.io/library/mariadb:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql:z
    ports:
      - 10001:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
